<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUebV0YB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUebV0YB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUebV0YB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUebV0YB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUebV0YB\App_KernelDevDebugContainer([
    'container.build_hash' => 'UebV0YB',
    'container.build_id' => '8a4285cb',
    'container.build_time' => 1777836994,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUebV0YB');
