<?php

namespace ContainerHGLgG7a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9kKwU2tService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9kKwU2t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9kKwU2t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['privates', '.errored..service_locator.9kKwU2t.Doctrine\\ORM\\EntityManagerInterface', NULL, 'Cannot autowire service ".service_locator.9kKwU2t": it references interface "Doctrine\\ORM\\EntityManagerInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'em' => 'Doctrine\\ORM\\EntityManagerInterface',
        ]);
    }
}
