<?php

namespace ContainerHGLgG7a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntityManagerInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9kKwU2t.Doctrine\ORM\EntityManagerInterface' shared service.
     *
     * @return \Doctrine\ORM\EntityManagerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9kKwU2t": it references interface "Doctrine\\ORM\\EntityManagerInterface" but no such service exists. Did you create a class that implements this interface?');
    }
}
