<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q_9qTUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q.9q_tU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.q.9q_tU.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.q.9q_tU": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'user' => 'App\\Entity\\User',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.q.9q_tU'])) {
            return $container->privates['.service_locator.q.9q_tU'];
        }

        return $container->privates['.service_locator.q.9q_tU'] = $instance;
    }
}
