<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PanwmF9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.panwmF9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'profile' => ['privates', '.errored..service_locator.panwmF9.App\\Entity\\Profile', NULL, 'Cannot autowire service ".service_locator.panwmF9": it needs an instance of "App\\Entity\\Profile" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'profile' => 'App\\Entity\\Profile',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.panwmF9'])) {
            return $container->privates['.service_locator.panwmF9'];
        }

        return $container->privates['.service_locator.panwmF9'] = $instance;
    }
}
