<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AHkHqmiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AHkHqmi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userProgressService' => ['privates', 'App\\Service\\UserProgressService', 'getUserProgressServiceService', true],
            'userSessionService' => ['privates', 'App\\Service\\UserSessionService', 'getUserSessionServiceService', false],
        ], [
            'userProgressService' => 'App\\Service\\UserProgressService',
            'userSessionService' => 'App\\Service\\UserSessionService',
        ]);

        if (isset($container->privates['.service_locator.AHkHqmi'])) {
            return $container->privates['.service_locator.AHkHqmi'];
        }

        return $container->privates['.service_locator.AHkHqmi'] = $instance;
    }
}
