<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YA46zmaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yA46zma' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tacheFocu' => ['privates', '.errored..service_locator.yA46zma.App\\Entity\\TacheFocus', NULL, 'Cannot autowire service ".service_locator.yA46zma": it needs an instance of "App\\Entity\\TacheFocus" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'tacheFocu' => 'App\\Entity\\TacheFocus',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.yA46zma'])) {
            return $container->privates['.service_locator.yA46zma'];
        }

        return $container->privates['.service_locator.yA46zma'] = $instance;
    }
}
