<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EwKW7qMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EwKW7qM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EwKW7qM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sousTacheRepository' => ['privates', 'App\\Repository\\SousTacheRepository', 'getSousTacheRepositoryService', true],
            'tacheFocusRepository' => ['privates', 'App\\Repository\\TacheFocusRepository', 'getTacheFocusRepositoryService', true],
        ], [
            'sousTacheRepository' => 'App\\Repository\\SousTacheRepository',
            'tacheFocusRepository' => 'App\\Repository\\TacheFocusRepository',
        ]);
    }
}
