<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GsANmcJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gsANmcJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'paginator' => '?',
        ]);

        if (isset($container->privates['.service_locator.gsANmcJ'])) {
            return $container->privates['.service_locator.gsANmcJ'];
        }

        return $container->privates['.service_locator.gsANmcJ'] = $instance;
    }
}
