<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M0TcLEAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m0TcLEA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userSessionService' => ['privates', 'App\\Service\\UserSessionService', 'getUserSessionServiceService', false],
        ], [
            'userSessionService' => 'App\\Service\\UserSessionService',
        ]);

        if (isset($container->privates['.service_locator.m0TcLEA'])) {
            return $container->privates['.service_locator.m0TcLEA'];
        }

        return $container->privates['.service_locator.m0TcLEA'] = $instance;
    }
}
