<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PTZJAspService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PTZJAsp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sousTache' => ['privates', '.errored..service_locator.PTZJAsp.App\\Entity\\SousTache', NULL, 'Cannot autowire service ".service_locator.PTZJAsp": it needs an instance of "App\\Entity\\SousTache" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'sousTache' => 'App\\Entity\\SousTache',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.PTZJAsp'])) {
            return $container->privates['.service_locator.PTZJAsp'];
        }

        return $container->privates['.service_locator.PTZJAsp'] = $instance;
    }
}
