<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminAiTestServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AdminAiTestService' shared autowired service.
     *
     * @return \App\Service\AdminAiTestService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/AdminAiTestService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/GeminiClientService.php';

        return $container->privates['App\\Service\\AdminAiTestService'] = new \App\Service\AdminAiTestService(new \App\Service\GeminiClientService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('GEMINI_API_KEY'), $container->getEnv('GEMINI_MODEL')));
    }
}
