<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminInsightsControllerresultsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NQgh7yA.App\Controller\AdminInsightsController::results()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'adminInsightsService' => ['privates', 'App\\Service\\AdminInsightsService', 'getAdminInsightsServiceService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'adminInsightsService' => 'App\\Service\\AdminInsightsService',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\AdminInsightsController::results()', $container);

        if (isset($container->privates['.service_locator.NQgh7yA.App\\Controller\\AdminInsightsController::results()'])) {
            return $container->privates['.service_locator.NQgh7yA.App\\Controller\\AdminInsightsController::results()'];
        }

        return $container->privates['.service_locator.NQgh7yA.App\\Controller\\AdminInsightsController::results()'] = $instance;
    }
}
