<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminAiPersistServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AdminAiPersistService' shared autowired service.
     *
     * @return \App\Service\AdminAiPersistService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/AdminAiPersistService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\AdminAiPersistService'])) {
            return $container->privates['App\\Service\\AdminAiPersistService'];
        }

        $instance = new \App\Service\AdminAiPersistService($a);

        if (isset($container->privates['App\\Service\\AdminAiPersistService'])) {
            return $container->privates['App\\Service\\AdminAiPersistService'];
        }

        return $container->privates['App\\Service\\AdminAiPersistService'] = $instance;
    }
}
