<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminStatisticsControllersendReminderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6uGY8yV.App\Controller\AdminStatisticsController::sendReminder()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'adminReminderMailer' => ['privates', 'App\\Service\\AdminReminderMailer', 'getAdminReminderMailerService', true],
        ], [
            'adminReminderMailer' => 'App\\Service\\AdminReminderMailer',
        ]))->withContext('App\\Controller\\AdminStatisticsController::sendReminder()', $container);

        if (isset($container->privates['.service_locator.6uGY8yV.App\\Controller\\AdminStatisticsController::sendReminder()'])) {
            return $container->privates['.service_locator.6uGY8yV.App\\Controller\\AdminStatisticsController::sendReminder()'];
        }

        return $container->privates['.service_locator.6uGY8yV.App\\Controller\\AdminStatisticsController::sendReminder()'] = $instance;
    }
}
