<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAiSousTacheGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AiSousTacheGenerator' shared autowired service.
     *
     * @return \App\Service\AiSousTacheGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/AiSousTacheGenerator.php';

        return $container->privates['App\\Service\\AiSousTacheGenerator'] = new \App\Service\AiSousTacheGenerator(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')));
    }
}
