<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminAiControllergenerateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BjabeOf.App\Controller\AdminAiController::generate()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'service' => ['privates', 'App\\Service\\AdminAiTestService', 'getAdminAiTestServiceService', true],
            'persistService' => ['privates', 'App\\Service\\AdminAiPersistService', 'getAdminAiPersistServiceService', true],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', true],
        ], [
            'service' => 'App\\Service\\AdminAiTestService',
            'persistService' => 'App\\Service\\AdminAiPersistService',
            'logger' => '?',
        ]))->withContext('App\\Controller\\AdminAiController::generate()', $container);

        if (isset($container->privates['.service_locator.BjabeOf.App\\Controller\\AdminAiController::generate()'])) {
            return $container->privates['.service_locator.BjabeOf.App\\Controller\\AdminAiController::generate()'];
        }

        return $container->privates['.service_locator.BjabeOf.App\\Controller\\AdminAiController::generate()'] = $instance;
    }
}
