<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminInsightsControlleranalyticsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F5PQm.d.App\Controller\AdminInsightsController::analytics()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'adminInsightsService' => ['privates', 'App\\Service\\AdminInsightsService', 'getAdminInsightsServiceService', true],
        ], [
            'adminInsightsService' => 'App\\Service\\AdminInsightsService',
        ]))->withContext('App\\Controller\\AdminInsightsController::analytics()', $container);

        if (isset($container->privates['.service_locator.F5PQm.d.App\\Controller\\AdminInsightsController::analytics()'])) {
            return $container->privates['.service_locator.F5PQm.d.App\\Controller\\AdminInsightsController::analytics()'];
        }

        return $container->privates['.service_locator.F5PQm.d.App\\Controller\\AdminInsightsController::analytics()'] = $instance;
    }
}
