<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAchievementControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BackOffice\AchievementController' shared autowired service.
     *
     * @return \App\Controller\BackOffice\AchievementController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BackOffice/AchievementController.php';

        $container->services['App\\Controller\\BackOffice\\AchievementController'] = $instance = new \App\Controller\BackOffice\AchievementController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\AchievementRepository'] ?? $container->load('getAchievementRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\BackOffice\\AchievementController', $container));

        return $instance;
    }
}
