<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FrontOffice\CommentController' shared autowired service.
     *
     * @return \App\Controller\FrontOffice\CommentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FrontOffice/CommentController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ProfanityService.php';

        $container->services['App\\Controller\\FrontOffice\\CommentController'] = $instance = new \App\Controller\FrontOffice\CommentController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\CommentRepository'] ?? $container->load('getCommentRepositoryService')), ($container->privates['App\\Service\\ProfanityService'] ??= new \App\Service\ProfanityService()), ($container->privates['App\\Service\\UserSessionService'] ?? self::getUserSessionServiceService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\FrontOffice\\CommentController', $container));

        return $instance;
    }
}
