<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontTestControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FrontTestController' shared autowired service.
     *
     * @return \App\Controller\FrontTestController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FrontTestController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/FrontTestService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/SentimentApiService.php';

        $container->services['App\\Controller\\FrontTestController'] = $instance = new \App\Controller\FrontTestController(($container->privates['App\\Repository\\GeneralTestRepository'] ?? $container->load('getGeneralTestRepositoryService')), ($container->privates['App\\Repository\\SpecificTestRepository'] ?? $container->load('getSpecificTestRepositoryService')), ($container->privates['App\\Repository\\GeneralAnswerRepository'] ?? $container->load('getGeneralAnswerRepositoryService')), ($container->privates['App\\Repository\\SpecificAnswerRepository'] ?? $container->load('getSpecificAnswerRepositoryService')), ($container->privates['App\\Service\\GeneralTestService'] ?? $container->load('getGeneralTestServiceService')), ($container->privates['App\\Service\\SpecificTestService'] ?? $container->load('getSpecificTestServiceService')), new \App\Service\FrontTestService(), ($container->privates['App\\Service\\MotivationalService'] ?? $container->load('getMotivationalServiceService')), new \App\Service\SentimentApiService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('SENTIMENT_API_URL'), $container->getEnv('QUOTE_API_KEY'), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'))), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\FrontTestController', $container));

        return $instance;
    }
}
