<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeneralTestServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\GeneralTestService' shared autowired service.
     *
     * @return \App\Service\GeneralTestService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/GeneralTestService.php';

        return $container->privates['App\\Service\\GeneralTestService'] = new \App\Service\GeneralTestService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\GeneralTestRepository'] ?? $container->load('getGeneralTestRepositoryService')), ($container->privates['App\\Repository\\GeneralQuestionRepository'] ?? $container->load('getGeneralQuestionRepositoryService')), ($container->privates['App\\Repository\\GeneralAnswerRepository'] ?? $container->load('getGeneralAnswerRepositoryService')));
    }
}
