<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMotivationalServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\MotivationalService' shared autowired service.
     *
     * @return \App\Service\MotivationalService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/MotivationalService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ExternalApiService.php';

        return $container->privates['App\\Service\\MotivationalService'] = new \App\Service\MotivationalService(new \App\Service\ExternalApiService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('QUOTE_API_URL'), $container->getEnv('QUOTE_API_KEY'), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'))));
    }
}
