<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BackOffice\PostController' shared autowired service.
     *
     * @return \App\Controller\BackOffice\PostController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BackOffice/PostController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ProfanityService.php';

        $container->services['App\\Controller\\BackOffice\\PostController'] = $instance = new \App\Controller\BackOffice\PostController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\PostRepository'] ?? $container->load('getPostRepositoryService')), ($container->privates['App\\Repository\\CommentRepository'] ?? $container->load('getCommentRepositoryService')), ($container->privates['App\\Repository\\SavesRepository'] ?? $container->load('getSavesRepositoryService')), ($container->privates['App\\Repository\\AchievementRepository'] ?? $container->load('getAchievementRepositoryService')), ($container->privates['App\\Service\\ProfanityService'] ??= new \App\Service\ProfanityService()), ($container->privates['App\\Service\\UserSessionService'] ?? self::getUserSessionServiceService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\BackOffice\\PostController', $container));

        return $instance;
    }
}
