<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSousTacheControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._7ugAbN.App\Controller\SousTacheController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._7ugAbN.App\\Controller\\SousTacheController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sousTache' => ['privates', '.errored..service_locator._7ugAbN.App\\Entity\\SousTache', NULL, 'Cannot autowire service ".service_locator._7ugAbN": it needs an instance of "App\\Entity\\SousTache" but this type has been excluded in "config/services.yaml".'],
        ], [
            'sousTache' => 'App\\Entity\\SousTache',
        ]))->withContext('App\\Controller\\SousTacheController::show()', $container);
    }
}
