<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSavesTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SavesType' shared autowired service.
     *
     * @return \App\Form\SavesType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SavesType.php';

        return $container->privates['App\\Form\\SavesType'] = new \App\Form\SavesType();
    }
}
