<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSousTacheControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EwKW7qM.App\Controller\BackOffice\SousTacheController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EwKW7qM.App\\Controller\\BackOffice\\SousTacheController::index()'] = ($container->privates['.service_locator.EwKW7qM'] ?? $container->load('get_ServiceLocator_EwKW7qMService'))->withContext('App\\Controller\\BackOffice\\SousTacheController::index()', $container);
    }
}
