<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpecificTestControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SpecificTestController' shared autowired service.
     *
     * @return \App\Controller\SpecificTestController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/SpecificTestController.php';

        $container->services['App\\Controller\\SpecificTestController'] = $instance = new \App\Controller\SpecificTestController(($container->privates['App\\Service\\SpecificTestService'] ?? $container->load('getSpecificTestServiceService')), ($container->privates['App\\Service\\GeneralTestService'] ?? $container->load('getGeneralTestServiceService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\SpecificTestController', $container));

        return $instance;
    }
}
