<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatistiqueControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ETPvFUu.App\Controller\StatistiqueController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ETPvFUu.App\\Controller\\StatistiqueController::index()'] = ($container->privates['.service_locator.ETPvFUu'] ?? $container->load('get_ServiceLocator_ETPvFUuService'))->withContext('App\\Controller\\StatistiqueController::index()', $container);
    }
}
