<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpecificTestServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SpecificTestService' shared autowired service.
     *
     * @return \App\Service\SpecificTestService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/SpecificTestService.php';

        return $container->privates['App\\Service\\SpecificTestService'] = new \App\Service\SpecificTestService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\SpecificTestRepository'] ?? $container->load('getSpecificTestRepositoryService')), ($container->privates['App\\Repository\\SpecificQuestionRepository'] ?? $container->load('getSpecificQuestionRepositoryService')), ($container->privates['App\\Repository\\SpecificAnswerRepository'] ?? $container->load('getSpecificAnswerRepositoryService')));
    }
}
