<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSousTache2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._7ugAbN.App\Entity\SousTache' shared service.
     *
     * @return \App\Entity\SousTache
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._7ugAbN": it needs an instance of "App\\Entity\\SousTache" but this type has been excluded in "config/services.yaml".');
    }
}
