<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionControllersetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m0TcLEA.App\Controller\SessionController::set()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.m0TcLEA'] ?? $container->load('get_ServiceLocator_M0TcLEAService'));

        if (isset($container->privates['.service_locator.m0TcLEA.App\\Controller\\SessionController::set()'])) {
            return $container->privates['.service_locator.m0TcLEA.App\\Controller\\SessionController::set()'];
        }

        $instance = $a->withContext('App\\Controller\\SessionController::set()', $container);

        if (isset($container->privates['.service_locator.m0TcLEA.App\\Controller\\SessionController::set()'])) {
            return $container->privates['.service_locator.m0TcLEA.App\\Controller\\SessionController::set()'];
        }

        return $container->privates['.service_locator.m0TcLEA.App\\Controller\\SessionController::set()'] = $instance;
    }
}
