<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpecificTestControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gsANmcJ.App\Controller\SpecificTestController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gsANmcJ.App\\Controller\\SpecificTestController::index()'] = ($container->privates['.service_locator.gsANmcJ'] ?? $container->load('get_ServiceLocator_GsANmcJService'))->withContext('App\\Controller\\SpecificTestController::index()', $container);
    }
}
