<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTacheFocusControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yA46zma.App\Controller\TacheFocusController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.yA46zma'] ?? $container->load('get_ServiceLocator_YA46zmaService'));

        if (isset($container->privates['.service_locator.yA46zma.App\\Controller\\TacheFocusController::delete()'])) {
            return $container->privates['.service_locator.yA46zma.App\\Controller\\TacheFocusController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\TacheFocusController::delete()', $container);

        if (isset($container->privates['.service_locator.yA46zma.App\\Controller\\TacheFocusController::delete()'])) {
            return $container->privates['.service_locator.yA46zma.App\\Controller\\TacheFocusController::delete()'];
        }

        return $container->privates['.service_locator.yA46zma.App\\Controller\\TacheFocusController::delete()'] = $instance;
    }
}
