<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTacheFocusControllershowHolidaysService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XSKQQpm.App\Controller\TacheFocusController::showHolidays()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XSKQQpm.App\\Controller\\TacheFocusController::showHolidays()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tacheFocu' => ['privates', '.errored..service_locator.XSKQQpm.App\\Entity\\TacheFocus', NULL, 'Cannot autowire service ".service_locator.XSKQQpm": it needs an instance of "App\\Entity\\TacheFocus" but this type has been excluded in "config/services.yaml".'],
            'holidayService' => ['privates', 'App\\Service\\HolidayService', 'getHolidayServiceService', true],
        ], [
            'tacheFocu' => 'App\\Entity\\TacheFocus',
            'holidayService' => 'App\\Service\\HolidayService',
        ]))->withContext('App\\Controller\\TacheFocusController::showHolidays()', $container);
    }
}
