<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTacheFocusControllerindex2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oUjwThx.App\Controller\TacheFocusController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oUjwThx.App\\Controller\\TacheFocusController::index()'] = ($container->privates['.service_locator.oUjwThx'] ?? $container->load('get_ServiceLocator_OUjwThxService'))->withContext('App\\Controller\\TacheFocusController::index()', $container);
    }
}
