<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTacheFocusControllergenerateAiSuggestionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qKVoIOG.App\Controller\TacheFocusController::generateAiSuggestions()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qKVoIOG.App\\Controller\\TacheFocusController::generateAiSuggestions()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tacheFocu' => ['privates', '.errored..service_locator.qKVoIOG.App\\Entity\\TacheFocus', NULL, 'Cannot autowire service ".service_locator.qKVoIOG": it needs an instance of "App\\Entity\\TacheFocus" but this type has been excluded in "config/services.yaml".'],
            'aiSousTacheGenerator' => ['privates', 'App\\Service\\AiSousTacheGenerator', 'getAiSousTacheGeneratorService', true],
        ], [
            'tacheFocu' => 'App\\Entity\\TacheFocus',
            'aiSousTacheGenerator' => 'App\\Service\\AiSousTacheGenerator',
        ]))->withContext('App\\Controller\\TacheFocusController::generateAiSuggestions()', $container);
    }
}
