<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTacheFocusControllerrecommendMusicService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Pe8njuO.App\Controller\TacheFocusController::recommendMusic()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Pe8njuO.App\\Controller\\TacheFocusController::recommendMusic()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tacheFocu' => ['privates', '.errored..service_locator.Pe8njuO.App\\Entity\\TacheFocus', NULL, 'Cannot autowire service ".service_locator.Pe8njuO": it needs an instance of "App\\Entity\\TacheFocus" but this type has been excluded in "config/services.yaml".'],
            'focusMusicService' => ['privates', 'App\\Service\\FocusMusicService', 'getFocusMusicServiceService', true],
        ], [
            'tacheFocu' => 'App\\Entity\\TacheFocus',
            'focusMusicService' => 'App\\Service\\FocusMusicService',
        ]))->withContext('App\\Controller\\TacheFocusController::recommendMusic()', $container);
    }
}
