<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTacheFocusControllergenerateAiAdviceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hVQ4nSe.App\Controller\TacheFocusController::generateAiAdvice()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hVQ4nSe.App\\Controller\\TacheFocusController::generateAiAdvice()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tacheFocu' => ['privates', '.errored..service_locator.hVQ4nSe.App\\Entity\\TacheFocus', NULL, 'Cannot autowire service ".service_locator.hVQ4nSe": it needs an instance of "App\\Entity\\TacheFocus" but this type has been excluded in "config/services.yaml".'],
            'aiTaskAdvisor' => ['privates', 'App\\Service\\AiTaskAdvisor', 'getAiTaskAdvisorService', true],
        ], [
            'tacheFocu' => 'App\\Entity\\TacheFocus',
            'aiTaskAdvisor' => 'App\\Service\\AiTaskAdvisor',
        ]))->withContext('App\\Controller\\TacheFocusController::generateAiAdvice()', $container);
    }
}
