<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTacheFocusControllerrecommendBooksService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kYrsPaL.App\Controller\TacheFocusController::recommendBooks()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kYrsPaL.App\\Controller\\TacheFocusController::recommendBooks()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tacheFocu' => ['privates', '.errored..service_locator.kYrsPaL.App\\Entity\\TacheFocus', NULL, 'Cannot autowire service ".service_locator.kYrsPaL": it needs an instance of "App\\Entity\\TacheFocus" but this type has been excluded in "config/services.yaml".'],
            'focusBookService' => ['privates', 'App\\Service\\FocusBookService', 'getFocusBookServiceService', true],
        ], [
            'tacheFocu' => 'App\\Entity\\TacheFocus',
            'focusBookService' => 'App\\Service\\FocusBookService',
        ]))->withContext('App\\Controller\\TacheFocusController::recommendBooks()', $container);
    }
}
