<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTacheFocusControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oUjwThx.App\Controller\BackOffice\TacheFocusController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.oUjwThx'] ?? $container->load('get_ServiceLocator_OUjwThxService'));

        if (isset($container->privates['.service_locator.oUjwThx.App\\Controller\\BackOffice\\TacheFocusController::index()'])) {
            return $container->privates['.service_locator.oUjwThx.App\\Controller\\BackOffice\\TacheFocusController::index()'];
        }

        $instance = $a->withContext('App\\Controller\\BackOffice\\TacheFocusController::index()', $container);

        if (isset($container->privates['.service_locator.oUjwThx.App\\Controller\\BackOffice\\TacheFocusController::index()'])) {
            return $container->privates['.service_locator.oUjwThx.App\\Controller\\BackOffice\\TacheFocusController::index()'];
        }

        return $container->privates['.service_locator.oUjwThx.App\\Controller\\BackOffice\\TacheFocusController::index()'] = $instance;
    }
}
