<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestLifecycleControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TestLifecycleController' shared autowired service.
     *
     * @return \App\Controller\TestLifecycleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TestLifecycleController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/TestLifecycleService.php';

        $container->services['App\\Controller\\TestLifecycleController'] = $instance = new \App\Controller\TestLifecycleController(($container->privates['App\\Service\\GeneralTestService'] ?? $container->load('getGeneralTestServiceService')), ($container->privates['App\\Service\\SpecificTestService'] ?? $container->load('getSpecificTestServiceService')), new \App\Service\TestLifecycleService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\TestLifecycleController', $container));

        return $instance;
    }
}
