<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTacheFocus2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Pe8njuO.App\Entity\TacheFocus' shared service.
     *
     * @return \App\Entity\TacheFocus
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Pe8njuO": it needs an instance of "App\\Entity\\TacheFocus" but this type has been excluded in "config/services.yaml".');
    }
}
