<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTacheFocusControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.K7XhTtU.App\Controller\TacheFocusController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.K7XhTtU.App\\Controller\\TacheFocusController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tacheFocu' => ['privates', '.errored..service_locator.K7XhTtU.App\\Entity\\TacheFocus', NULL, 'Cannot autowire service ".service_locator.K7XhTtU": it needs an instance of "App\\Entity\\TacheFocus" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tacheFocu' => 'App\\Entity\\TacheFocus',
        ]))->withContext('App\\Controller\\TacheFocusController::show()', $container);
    }
}
