<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAdminControllerprofileDeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.panwmF9.App\Controller\UserAdminController::profileDelete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.panwmF9'] ?? $container->load('get_ServiceLocator_PanwmF9Service'));

        if (isset($container->privates['.service_locator.panwmF9.App\\Controller\\UserAdminController::profileDelete()'])) {
            return $container->privates['.service_locator.panwmF9.App\\Controller\\UserAdminController::profileDelete()'];
        }

        $instance = $a->withContext('App\\Controller\\UserAdminController::profileDelete()', $container);

        if (isset($container->privates['.service_locator.panwmF9.App\\Controller\\UserAdminController::profileDelete()'])) {
            return $container->privates['.service_locator.panwmF9.App\\Controller\\UserAdminController::profileDelete()'];
        }

        return $container->privates['.service_locator.panwmF9.App\\Controller\\UserAdminController::profileDelete()'] = $instance;
    }
}
