<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserStatisticsControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TkheBeg.App\Controller\UserStatisticsController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userStatisticsService' => ['privates', 'App\\Service\\UserStatisticsService', 'getUserStatisticsServiceService', true],
            'motivationalService' => ['privates', 'App\\Service\\MotivationalService', 'getMotivationalServiceService', true],
            'chartBuilder' => ['privates', 'chartjs.builder', 'getChartjs_BuilderService', true],
            'userSessionService' => ['privates', 'App\\Service\\UserSessionService', 'getUserSessionServiceService', false],
        ], [
            'userStatisticsService' => 'App\\Service\\UserStatisticsService',
            'motivationalService' => 'App\\Service\\MotivationalService',
            'chartBuilder' => '?',
            'userSessionService' => 'App\\Service\\UserSessionService',
        ]))->withContext('App\\Controller\\UserStatisticsController::index()', $container);

        if (isset($container->privates['.service_locator.TkheBeg.App\\Controller\\UserStatisticsController::index()'])) {
            return $container->privates['.service_locator.TkheBeg.App\\Controller\\UserStatisticsController::index()'];
        }

        return $container->privates['.service_locator.TkheBeg.App\\Controller\\UserStatisticsController::index()'] = $instance;
    }
}
