<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAiCoachServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\UserAiCoachService' shared autowired service.
     *
     * @return \App\Service\UserAiCoachService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/UserAiCoachService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/GroqClientService.php';

        return $container->privates['App\\Service\\UserAiCoachService'] = new \App\Service\UserAiCoachService(new \App\Service\GroqClientService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('GROQ_API_KEY'), $container->getEnv('GROQ_MODEL')));
    }
}
