<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProgressControllerhistoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DhYQGh7.App\Controller\UserProgressController::history()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userProgressService' => ['privates', 'App\\Service\\UserProgressService', 'getUserProgressServiceService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'userSessionService' => ['privates', 'App\\Service\\UserSessionService', 'getUserSessionServiceService', false],
        ], [
            'userProgressService' => 'App\\Service\\UserProgressService',
            'paginator' => '?',
            'userSessionService' => 'App\\Service\\UserSessionService',
        ]))->withContext('App\\Controller\\UserProgressController::history()', $container);

        if (isset($container->privates['.service_locator.DhYQGh7.App\\Controller\\UserProgressController::history()'])) {
            return $container->privates['.service_locator.DhYQGh7.App\\Controller\\UserProgressController::history()'];
        }

        return $container->privates['.service_locator.DhYQGh7.App\\Controller\\UserProgressController::history()'] = $instance;
    }
}
