<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAiChatControllerchatService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VTUaejZ.App\Controller\UserAiChatController::chat()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userSessionService' => ['privates', 'App\\Service\\UserSessionService', 'getUserSessionServiceService', false],
        ], [
            'entityManager' => '?',
            'userSessionService' => 'App\\Service\\UserSessionService',
        ]))->withContext('App\\Controller\\UserAiChatController::chat()', $container);

        if (isset($container->privates['.service_locator.VTUaejZ.App\\Controller\\UserAiChatController::chat()'])) {
            return $container->privates['.service_locator.VTUaejZ.App\\Controller\\UserAiChatController::chat()'];
        }

        return $container->privates['.service_locator.VTUaejZ.App\\Controller\\UserAiChatController::chat()'] = $instance;
    }
}
