<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAdminControllerprofileListService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h_PM3aR.App\Controller\UserAdminController::profileList()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h_PM3aR.App\\Controller\\UserAdminController::profileList()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\ProfileRepository', 'getProfileRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\ProfileRepository',
        ]))->withContext('App\\Controller\\UserAdminController::profileList()', $container);
    }
}
