<?php

namespace ContainerUebV0YB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserPdfControllerexportStatisticsPdfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AHkHqmi.App\Controller\UserPdfController::exportStatisticsPdf()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.AHkHqmi'] ?? $container->load('get_ServiceLocator_AHkHqmiService'));

        if (isset($container->privates['.service_locator.AHkHqmi.App\\Controller\\UserPdfController::exportStatisticsPdf()'])) {
            return $container->privates['.service_locator.AHkHqmi.App\\Controller\\UserPdfController::exportStatisticsPdf()'];
        }

        $instance = $a->withContext('App\\Controller\\UserPdfController::exportStatisticsPdf()', $container);

        if (isset($container->privates['.service_locator.AHkHqmi.App\\Controller\\UserPdfController::exportStatisticsPdf()'])) {
            return $container->privates['.service_locator.AHkHqmi.App\\Controller\\UserPdfController::exportStatisticsPdf()'];
        }

        return $container->privates['.service_locator.AHkHqmi.App\\Controller\\UserPdfController::exportStatisticsPdf()'] = $instance;
    }
}
