front_controllers:
    resource:
        path: ../src/Controller/FrontOffice/
        namespace: App\Controller\FrontOffice
    type: attribute

back_controllers:
    resource:
        path: ../src/Controller/BackOffice/
        namespace: App\Controller\BackOffice
    type: attribute
