parameters:
    resend.api_key: '%env(RESEND_API_KEY)%'
    
    resend.from_name: '%env(RESEND_FROM_NAME)%'
    resend.reply_to: '%env(RESEND_REPLY_TO)%'
    sentiment.api_url: '%env(SENTIMENT_API_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Quotes API
    App\Service\ExternalApiService:
        arguments:
            $quoteApiUrl: '%env(QUOTE_API_URL)%'
            $quoteApiKey: '%env(QUOTE_API_KEY)%'

    # Sentiment API
    App\Service\SentimentApiService:
        arguments:
            $sentimentApiUrl: '%sentiment.api_url%'
            $apiKey: '%env(QUOTE_API_KEY)%'

    # Gemini (Admin IA)
    App\Service\GeminiClientService:
        arguments:
            $apiKey: '%env(GEMINI_API_KEY)%'
            $model: '%env(GEMINI_MODEL)%'

    # Groq (User chatbot)
    App\Service\GroqClientService:
        arguments:
            $apiKey: '%env(GROQ_API_KEY)%'
            $model: '%env(GROQ_MODEL)%'

   